// Generates pinyin lookup data from pinyin-pro for offline use
const { pinyin } = require('pinyin-pro');
const fs = require('fs');
const path = require('path');

const data = {};

// CJK Unified Ideographs basic block
for (let i = 0x4e00; i <= 0x9fff; i++) {
  const char = String.fromCharCode(i);
  const result = pinyin(char, { toneType: 'symbol', type: 'array' });
  if (result && result[0] && result[0] !== char) {
    // For polyphonic characters, pinyin-pro returns the most common reading
    data[char] = result[0];
  }
}

const count = Object.keys(data).length;
const output = `// Auto-generated by gen-pinyin.js | ${count} entries\n// Do not edit manually\nwindow.PINYIN_DATA = ${JSON.stringify(data)};`;

const outPath = path.join(__dirname, 'js', 'pinyin-data.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, output, 'utf-8');
console.log(`Generated ${count} pinyin entries -> ${outPath}`);
